version: "3.3"

services:
  nextjs:
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/node_modules
      - ./app/.next
~                                                                                                                                                                                                                                             
~